package entity;
// Generated Apr 28, 2020 2:07:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer proId;
     private SubCategory subCategory;
     private String proName;
     private int proQty;
     private double proPrize;
     private String proUrl;
     private String proDesc;
     private Set proOrderDetailses = new HashSet(0);

    public Product() {
    }

	
    public Product(SubCategory subCategory, String proName, int proQty, double proPrize, String proUrl, String proDesc) {
        this.subCategory = subCategory;
        this.proName = proName;
        this.proQty = proQty;
        this.proPrize = proPrize;
        this.proUrl = proUrl;
        this.proDesc = proDesc;
    }
    public Product(SubCategory subCategory, String proName, int proQty, double proPrize, String proUrl, String proDesc, Set proOrderDetailses) {
       this.subCategory = subCategory;
       this.proName = proName;
       this.proQty = proQty;
       this.proPrize = proPrize;
       this.proUrl = proUrl;
       this.proDesc = proDesc;
       this.proOrderDetailses = proOrderDetailses;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }
    public double getProPrize() {
        return this.proPrize;
    }
    
    public void setProPrize(double proPrize) {
        this.proPrize = proPrize;
    }
    public String getProUrl() {
        return this.proUrl;
    }
    
    public void setProUrl(String proUrl) {
        this.proUrl = proUrl;
    }
    public String getProDesc() {
        return this.proDesc;
    }
    
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc;
    }
    public Set getProOrderDetailses() {
        return this.proOrderDetailses;
    }
    
    public void setProOrderDetailses(Set proOrderDetailses) {
        this.proOrderDetailses = proOrderDetailses;
    }




}


