package entity;
// Generated Apr 28, 2020 2:07:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private Integer orderId;
     private DeliveryCost deliveryCost;
     private ShopUser shopUser;
     private int proId;
     private Date orderDate;
     private int orderQty;
     private double totalPrize;
     private String orderStatus;
     private Set proOrderDetailses = new HashSet(0);

    public ProOrder() {
    }

	
    public ProOrder(DeliveryCost deliveryCost, ShopUser shopUser, int proId, Date orderDate, int orderQty, double totalPrize, String orderStatus) {
        this.deliveryCost = deliveryCost;
        this.shopUser = shopUser;
        this.proId = proId;
        this.orderDate = orderDate;
        this.orderQty = orderQty;
        this.totalPrize = totalPrize;
        this.orderStatus = orderStatus;
    }
    public ProOrder(DeliveryCost deliveryCost, ShopUser shopUser, int proId, Date orderDate, int orderQty, double totalPrize, String orderStatus, Set proOrderDetailses) {
       this.deliveryCost = deliveryCost;
       this.shopUser = shopUser;
       this.proId = proId;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrize = totalPrize;
       this.orderStatus = orderStatus;
       this.proOrderDetailses = proOrderDetailses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public DeliveryCost getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(DeliveryCost deliveryCost) {
        this.deliveryCost = deliveryCost;
    }
    public ShopUser getShopUser() {
        return this.shopUser;
    }
    
    public void setShopUser(ShopUser shopUser) {
        this.shopUser = shopUser;
    }
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }
    public double getTotalPrize() {
        return this.totalPrize;
    }
    
    public void setTotalPrize(double totalPrize) {
        this.totalPrize = totalPrize;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getProOrderDetailses() {
        return this.proOrderDetailses;
    }
    
    public void setProOrderDetailses(Set proOrderDetailses) {
        this.proOrderDetailses = proOrderDetailses;
    }




}


